create or replace TABLE SWIB_RND.ERIN_ESCOBAR.BRANCH_SUPPLIER (
	BRANCH_ID NUMBER(38,0) NOT NULL,
	SUPPLIER_NAME VARCHAR(40) NOT NULL,
	SUPPLY_TYPE VARCHAR(40),
	primary key (BRANCH_ID, SUPPLIER_NAME)
);