create or replace TABLE SWIB_RND.ERIN_ESCOBAR.EMPLOYEE (
	EMP_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(40),
	LAST_NAME VARCHAR(40),
	BIRTH_DAY DATE,
	SEX VARCHAR(1),
	SALARY NUMBER(38,0),
	SUPER_ID NUMBER(38,0),
	BRANCH_ID NUMBER(38,0),
	primary key (EMP_ID)
);